### ISSUE TITLE
Double borders between buttons, too much vertical space taken in narrow layout

### ISSUE THREAD

**Issue by dandv** [ianmartorell/meteor-accounts-ui-bootstrap-3#103]
Not a huge deal, but on narrow screens, there are two borders visible between each two buttons:

![image](https://cloud.githubusercontent.com/assets/33569/7118840/968d1246-e1b6-11e4-9694-233c5149bb90.png)

The screenshot in #61 looks similar.

**Comment by dandv** [comment]
Thanks, that was quick!

**Comment by ianmartorell** [comment]
:D
