### ISSUE TITLE
EN instead of NL for language

### ISSUE THREAD

**Issue by ethnp** [ianmartorell/meteor-accounts-ui-bootstrap-3#106]
The dutch language has en in it so that it displays dutch for the english language.

**Comment by ianmartorell** [comment]
Oh shit you're right, that's pretty bad

**Comment by ethnp** [comment]
No worries man, happens :)




Can you fix it? We’re at a hackathon user your module!



Kind Regards,Ethan Presberg





Facebook | Google+ | @ethnp | LinkedIn


ethanpresberg.com

**Comment by ianmartorell** [comment]
Done, good luck with the hackathon!!

**Comment by ethnp** [comment]
Thanks!

**Comment by louwers** [comment]
Oops! Sorry guys!
Glad it's fixed.

**Comment by ethnp** [comment]
You&#8217;ve been invited!

On Airbnb you can discover unique places to stay from local hosts, all over the world.


Simply sign up by June 28, 2015 to get $25 off your first trip of $75 or more.





Accept invitation
http://www.airbnb.com/c/epresberg?eluid=0&euid=40ce3e7e-276c-c5e2-67a9-c00a99ad36a3&ri=21783168&s=1

Thanks,
The Airbnb Team

P.O. Box 410807, San Francisco, CA 94121

Unsubscribe
https://www.airbnb.com/email/unsubscribe?token=eyJlbWFpbF9hZGRyZXNzIjoicmVwbHkrMDAxNDI3ZWQzM2VmNzU3NGU4MjhmNDQzYTMzZTUxMzBmMjgxNTcwYTdjMzk0MDU2OTJjZjAwMDAwMDAxMTE0YTY5ZWE5MmExNjljZTA0MjFlYzZmQHJlcGx5LmdpdGh1Yi5jb20iLCJjYXRlZ29yeSI6InJlZmVycmFscyIsInRlbXBsYXRlIjoiaW52aXRhdGlvbiIsInV1aWQiOiI0MGNlM2U3ZS0yNzZjLWM1ZTItNjdhOS1jMDBhOTlhZDM2YTMifQ==&mac=mp7lGRGm0qD4AWJe0NuVEyi5Rzk=

### Airbnb ###

**Comment by ethnp** [comment]
Remember to accept your invitation!

Your friend Ethan gave you $25 to try out Airbnb, a marketplace where you can rent unique, local accommodations, on any budget, anywhere in the world.

You haven't claimed your credit yet - just click below and it will get automatically applied to your first trip!


Minimum booking value $75.



Accept invitation
http://www.airbnb.com/c/epresberg?eluid=3&euid=daad14d7-7bb6-c07d-c5e5-9f1dbaa2fa70&ri=21783168&s=1

Thanks,
The Airbnb Team

P.O. Box 410807, San Francisco, CA 94121

Unsubscribe
https://www.airbnb.com/email/unsubscribe?token=eyJlbWFpbF9hZGRyZXNzIjoicmVwbHkrMDAxNDI3ZWQzM2VmNzU3NGU4MjhmNDQzYTMzZTUxMzBmMjgxNTcwYTdjMzk0MDU2OTJjZjAwMDAwMDAxMTE0YTY5ZWE5MmExNjljZTA0MjFlYzZmQHJlcGx5LmdpdGh1Yi5jb20iLCJjYXRlZ29yeSI6InJlZmVycmFscyIsInRlbXBsYXRlIjoiaW52aXRhdGlvbl9yZW1pbmRlciIsInV1aWQiOiJkYWFkMTRkNy03YmI2LWMwN2QtYzVlNS05ZjFkYmFhMmZhNzAifQ==&mac=naxRFv5aQhcLNFydMIKBYbZ90Fc=

### Airbnb ###
