### ISSUE TITLE
Misaligned buttons for the Google configuration steps

### ISSUE THREAD

**Issue by dandv** [ianmartorell/meteor-accounts-ui-bootstrap-3#107]
![image](https://cloud.githubusercontent.com/assets/33569/7263987/7dc110ba-e83b-11e4-89de-922387729465.png)

**Comment by ianmartorell** [comment]
Not sure what causes this, but it doesn't happen without fezvrasta's theme. Disabling the margin rule on `.btn` makes it go away, but I don't think it's the culprit.
