### ISSUE TITLE
Google OAuth needs `?close` appended to URL

### ISSUE THREAD

**Issue by dandv** [ianmartorell/meteor-accounts-ui-bootstrap-3#109]
I initially thought this was a Meteor issue and reported it at https://github.com/meteor/meteor/issues/4246, but without `accounts-ui-bootstrap-3`, I can't reproduce it.

![image](https://cloud.githubusercontent.com/assets/33569/7264886/569bbd36-e846-11e4-941b-cad0cfb77dab.png)

Nothing special to reproduce; just create the skeleton app, `meteor add accounts-google accounts-ui-bootstrap-3 twbs:bootstrap` and add `{{> loginButtons}}`. Then configure authentication with Google.

Here's a reproduction repo anyway: https://github.com/dandv/meteor-issue-4224

**Comment by ecwyne** [comment]
I believe this is because ian:accounts-ui-bootstrap-3 is using [accounts-oauth@1.0.0](https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3/blob/master/package.js#L25) the most recent version is 1.1.5

**Comment by ecwyne** [comment]
Figured it out!

The method call [here](https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3/blob/master/login_buttons_dialogs.js#L210) is expecting a `loginStyle` property that is either `popup` or `redirect`. If that property is not present then the `?close` is added to the redirectURI [here](https://github.com/meteor/meteor/blob/master/packages/oauth/oauth_common.js#L11)

**Comment by ianmartorell** [comment]
Wow @ecwyne, that's definitely it! I'll update the package in a moment

**Comment by dandv** [comment]
Thank you gentlemen.  :cool:
