### ISSUE TITLE
Compatibility with several Bootswatch themes

### ISSUE THREAD

**Issue by dandv** [ianmartorell/meteor-accounts-ui-bootstrap-3#110]
I've created a repo at https://github.com/dandv/accounts-ui-bootstrap-3-with-themes testing accounts-ui-bootstrap-3 with all free [Bootswatch themese](https://bootswatch.com/). Some of them cause the "Forgot password?" and "Create account" links to be barely distinguishable from the background.

Looks like an issue with those themes though. Maybe that's the same problem with `bootstrap-material-design`, despite [what @fezvrasta says](https://github.com/FezVrasta/bootstrap-material-design/issues/565#issuecomment-95255619)?

**Comment by ianmartorell** [comment]
It simply doesn't look like these themes have accounted for a dropdown in the navbar. I'm thinking a possible solution could be to set the dropdown's background to the color of the body, but then the themes will probably still override it to the navbar color on smaller screens, and having a background color different than the navbar might not look good either...

**Comment by ianmartorell** [comment]
Actually, many of the themes set their own dropdown background on wide screens as well, so that makes me thing it's a bug on the specific themes. They should make sure the colors look good on whatever background they set.

**Comment by dandv** [comment]
> It simply doesn't look like these themes have accounted for a dropdown in the navbar.

I'd agree with that. Might be worth filing tickets with https://github.com/thomaspark/bootswatch. They're super responsive when it comes to addressing issues.

**Comment by dandv** [comment]
I've [filed the ticket](https://github.com/thomaspark/bootswatch/issues/447#event-293627254) and @thomaspark fixed it (thanks!)

**Comment by ianmartorell** [comment]
Oooh nice!! Closing this then

**Comment by karlitos** [comment]
I just tried the slate and cyborg theme as meteor packages (bootswatch:slate, bootswatch:cyborg), but they seems not to be working with meteor-accounts-ui-bootstrap-3. The theme is applied fine, the {{> loginButtons}} helper creates login button in the navbar but nothing happens if I try to click it.
