### ISSUE TITLE
How can I add a redio group into the signup form?

### ISSUE THREAD

**Issue by ValenW** [ianmartorell/meteor-accounts-ui-bootstrap-3#113]
I want to add a redio group into the signup from, my code is like this:
![image](https://cloud.githubusercontent.com/assets/8122612/7331639/d47695b2-eb4a-11e4-9c31-7f8d78d485e0.png)

but it seems like this:
![image](https://cloud.githubusercontent.com/assets/8122612/7331642/02827dcc-eb4b-11e4-971e-e2ff8dc1164c.png)

so how can I add a redio group correctly? :)

**Comment by sferoze** [comment]
The radio buttons in the example do not work for me to. This is a bug.

**Comment by ianmartorell** [comment]
This was implemented in #124, check the screenshots there and the config in the README
