### ISSUE TITLE
Logging user password in plaintext to console

### ISSUE THREAD

**Issue by saads** [ianmartorell/meteor-accounts-ui-bootstrap-3#114]
After creating a new user in the UI I noticed that the password I typed in was logged to the console and appeared in plain text.  This probably shouldn't happen for security reasons?  

In file `login_buttons_dropdown.js` there is a call to `console.log(options)` on line 590.

![screenshot from 2015-04-27 00 23 04](https://cloud.githubusercontent.com/assets/434665/7339114/e8c523d8-ec73-11e4-9e06-b86204c1f3f2.png)
---------------------------------------
![screenshot from 2015-04-27 00 25 45](https://cloud.githubusercontent.com/assets/434665/7339118/060a3df2-ec74-11e4-95f9-42472aa296da.png)

**Comment by ianmartorell** [comment]
The password is not being sent to the server in plain text, but you're totally right. I must've left it there from debugging accidentally
