### ISSUE TITLE
Prevent Changing of Password

### ISSUE THREAD

**Issue by nspangler** [ianmartorell/meteor-accounts-ui-bootstrap-3#117]
As per https://github.com/meteor-useraccounts/core/blob/master/Guide.md#configuration-api ,   

     AccountsTemplates.configure({
        enablePasswordChange: false
     })

to prevent the changing of a password. Does this package offer anything similar?

**Comment by ianmartorell** [comment]
Not yet!

**Comment by nspangler** [comment]
@ianmartorell thanks.
