### ISSUE TITLE
How to set the user login only one at the same time?

### ISSUE THREAD

**Issue by yuomtheara** [ianmartorell/meteor-accounts-ui-bootstrap-3#120]
I want to set the user can login only one at the same time.
For example, I have "theara" user account to login app. When I login on PC1 (online), so I can't use the same user to login on PC2 (local network).
How to check this or solve?

**Comment by ianmartorell** [comment]
While this would make for an interesting feature, I think it's out of the scope of this package. You could try setting a flag on the user document on login and unsetting it on logout. Then just return false with [this function](http://docs.meteor.com/#/full/accounts_validateloginattempt) whenever the flag is set.
