### ISSUE TITLE
Config options not available

### ISSUE THREAD

**Issue by pcasso** [ianmartorell/meteor-accounts-ui-bootstrap-3#123]
forbidClientAccountCreation,
enablePasswordChange
not available displays key not found error

**Comment by ianmartorell** [comment]
Hi, forbidClientAccountCreation is a config option in `Accounts`, not `Accounts.ui`, so it's not controlled by this package. Here's [a link to the docs](http://docs.meteor.com/#/full/accounts_config). I don't know about enablePasswordChange though.
