### ISSUE TITLE
Very big size of inpunt field for form "Reset your password"

### ISSUE THREAD

**Issue by comerc** [ianmartorell/meteor-accounts-ui-bootstrap-3#126]
May be need change css.

**Comment by ianmartorell** [comment]
What's the problem exactly? Can you post a screenshot?

**Comment by comerc** [comment]
![reset_password](https://cloud.githubusercontent.com/assets/1025241/7940293/a3ee8d10-0958-11e5-852f-c6d7f32d0775.jpg)

**Comment by ianmartorell** [comment]
You're right, they were a bit wide, I think they're better now
