### ISSUE TITLE
android

### ISSUE THREAD

**Issue by interfaith** [ianmartorell/meteor-accounts-ui-bootstrap-3#127]
fails to show on android
or will show ONE time
then disappear forever

**Comment by interfaith** [comment]
updating server fixed the login.
now the navigation bar css has dropped out,leaving a vertical menu without css ?

**Comment by ianmartorell** [comment]
Works fine on Android for me. It sounds like you have a conflicting package.

**Comment by interfaith** [comment]
It does work as advertised. However with crosswalk as the webview
component for cordova, a memory problem as emerged. Login appears
when using "4g data", not when using wifi ? Chrome works ok on wifi,
again memory becomes a problem. ancestorgram.com is the demo site. Too
much javascript I guess.

On Sun, Jun 7, 2015 at 5:40 AM, Ian Martorell <notifications@github.com>
wrote:

> Works fine on Android for me. It sounds like you have a conflicting
> package.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3/issues/127#issuecomment-109729992>
> .
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by ianmartorell** [comment]
I can see the dropdown on your test site just fine. I've tried it on Android using both Chrome and Firefox on 4G and Wifi. No problems here. It might be that it takes a bit to load on your device?

**Comment by interfaith** [comment]
Yes, I will upgrade the wifi.
Thx !

On Sun, Jun 7, 2015 at 8:49 AM, Ian Martorell <notifications@github.com>
wrote:

> I can see the dropdown on your test site just fine. I've tried it on
> Android using both Chrome and Firefox on 4G and Wifi. No problems here. It
> might be that it takes a bit to load on your device?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3/issues/127#issuecomment-109748883>
> .
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
