### ISSUE TITLE
Sign in only

### ISSUE THREAD

**Issue by artem-stepanov** [ianmartorell/meteor-accounts-ui-bootstrap-3#130]
Need add fix
```
Template._loginButtonsLoggedOutDropdown.helpers({
    forbidClientAccountCreation: function() {
        return Accounts._options.forbidClientAccountCreation;
    }
});
```

**Comment by ianmartorell** [comment]
This is already there, in file [login_buttons_dropdown.js#L211](../blob/master/login_buttons_dropdown.js#L211).

**Comment by artem-stepanov** [comment]
It`s not working, because Template have name "_loginButtonsLoggedOutDropdown", not "_loginButtonsLoggedOutAllServices" https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3/blob/master/login_buttons_dropdown.html#L42
