### ISSUE TITLE
Extra Field config interaction not working with checkbox and radio

### ISSUE THREAD

**Issue by sday** [ianmartorell/meteor-accounts-ui-bootstrap-3#137]
With radio buttons and check boxes they display correctly but I cannot interact with them.  Other field types work as expected.

Accounts.ui.config({
    forceEmailLowercase: true,
    requestPermissions: {},
    extraSignupFields: [{
        fieldName: 'terms',
        fieldLabel: 'I accept the terms and conditions',
        inputType: 'checkbox',
        visible: true
    }]
});

When I click on the checkbox, no check appears.  Same with radio buttons.  I tried the example in the readme and both radiobuttons and checkboxes fail to work.

![screen shot 2015-07-01 at 9 39 15 am](https://cloud.githubusercontent.com/assets/4720262/8459927/4fa1d3dc-1fd5-11e5-829c-37e036d5e504.png)

Thoughts?

**Comment by ianmartorell** [comment]
Maybe a theme issue? What is it you're using?

**Comment by sday** [comment]
That could very well be as I'm just getting my feet wet with meteor and I'm doing that with https://wrapbootstrap.com/theme/inspinia-responsive-admin-theme-WB0R5L90S

As my theme.

**Comment by ianmartorell** [comment]
Hmm then I've got no way to test it, but you should be able to remove the theme and see if it works then. I've got no issues with your code on a barebones Meteor app.

**Comment by sday** [comment]
Thanks, I'll do more digging.
