### ISSUE TITLE
case of email being considered when logging in

### ISSUE THREAD

**Issue by dpatte** [ianmartorell/meteor-accounts-ui-bootstrap-3#138]
If an account was created with xyz@example.com
the user cannot log in unless they match the case that they used when creating the account.

ie:  XYZ@example.com does not work to log in to the above account.

I believe that case should be ignored wherever email addresses are used.

**Comment by ianmartorell** [comment]
Actually, this is not handled by this package, but by [`accounts-password`](http://docs.meteor.com/#/full/meteor_loginwithpassword)

**Comment by dpatte** [comment]
Hi Ian. I'd be fine with all emails being made lowercase on signup. Perhaps you could make it an option?

**Comment by ianmartorell** [comment]
[That's already an option](https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3#forcing-lowercase-username-andor-password)! :P

**Comment by dpatte** [comment]
OOps, I missed that. Thank you.!
