### ISSUE TITLE
the arrow moved to next row when the name is long

### ISSUE THREAD

**Issue by Zane-XY** [ianmartorell/meteor-accounts-ui-bootstrap-3#140]
For some user with long user name, the UI doesn't looks right, checkout the screen shot.

<img width="327" alt="screenshot at jul 06 10-46-38" src="https://cloud.githubusercontent.com/assets/2939476/8514975/7359df86-23cc-11e5-894c-730e08ae4e22.png">

**Comment by ianmartorell** [comment]
I don't have this problem. Can you check if it happens only with long usernames? Also check with a new Meteor app. I just tried this on the latest version of the package and: 

![screen shot 2015-07-13 at 14 26 28](https://cloud.githubusercontent.com/assets/318800/8649536/8951f31a-296b-11e5-8562-8a8199098985.png)

**Comment by Zane-XY** [comment]
I forgot to mention, it's displaying all right in Firefox, but not in Chrome, the screenshot is taken from Chrome.

**Comment by ianmartorell** [comment]
I use Chrome as well, that screenshot I posted was from Chrome!

**Comment by ianmartorell** [comment]
(Misclick)

**Comment by ianmartorell** [comment]
Haven't been able to reproduce, so closing
