### ISSUE TITLE
Any way to tell the user he has successfully reseted his password?

### ISSUE THREAD

**Issue by steph643** [ianmartorell/meteor-accounts-ui-bootstrap-3#145]
When a user resets his password, the reset modal disappears with no confirmation message. Is there a way to display a confirmation popup, or to have the reset modal staying open with a conformation message?

**Comment by ianmartorell** [comment]
I've fixed this so there's a confirmation message, but beware that it will go away on a page refresh or hot code reload. I don't think it's worth fixing though.

I'm not sure why you said "verify their email" in the title though, your explanation doesn't say anything about email.

**Comment by steph643** [comment]
Great, thanks!
