### ISSUE TITLE
Invisible create account button when using Fezvrasta's materialize package

### ISSUE THREAD

**Issue by ldthorne** [ianmartorell/meteor-accounts-ui-bootstrap-3#146]
Hey! Thanks so much for your work! I'm using your accounts package and Fezvrasta's materialize package to materialize the app, and I'm having an issue right now in which the create account button is invisible on a smaller screen (i.e., mobile).  You can still click on it, but you can't see it unless it's a desktop size. Do you have any ideas how to fix this? Thanks so much!!

**Comment by ianmartorell** [comment]
Are you talking about [fezvrasta:bootstrap-material-design](https://github.com/FezVrasta/bootstrap-material-design)?

**Comment by ianmartorell** [comment]
#104
