### ISSUE TITLE
removed accounts-ui but site is still blank

### ISSUE THREAD

**Issue by maxshen1996** [ianmartorell/meteor-accounts-ui-bootstrap-3#148]
After removing accounts-ui and adding accounts-ui-bootstrap-3, the meteor app does not display anything. Removing the package fixes the problem.

Here's the error in the web console:
TypeError: Template._resetPasswordDialog.onRendered is not a function ian_accounts-ui-bootstrap-3.js:4407:1
TypeError: Package['ian:accounts-ui-bootstrap-3'] is undefined global-imports.js:5:0
ReferenceError: Template is not defined template.answer.js:2:0
ReferenceError: Template is not defined template.answerSubmit.js:2:0
ReferenceError: Template is not defined template.answerpage.js:2:0
ReferenceError: Template is not defined template.homepage.js:2:0
ReferenceError: Template is not defined template.layout.js:2:0
ReferenceError: Template is not defined template.loading.js:2:0
ReferenceError: Template is not defined template.mainpage.js:2:0
ReferenceError: Template is not defined template.myQuestions.js:2:0
ReferenceError: Template is not defined template.notFound.js:2:0
ReferenceError: Template is not defined template.question.js:2:0
ReferenceError: Template is not defined template.unanswered.js:2:0
ReferenceError: Mongo is not defined answers.js:2:0
ReferenceError: Mongo is not defined questions.js:2:0
ReferenceError: Template is not defined answer.js:1:12
ReferenceError: Template is not defined answerSubmit.js:2:0
ReferenceError: Template is not defined answerpage.js:1:12
ReferenceError: Template is not defined homepage.js:1:12
ReferenceError: Template is not defined layout.js:7:0
ReferenceError: Template is not defined myQuestions.js:1:12
ReferenceError: Template is not defined question.js:1:12
ReferenceError: Template is not defined unanswered.js:1:12
ReferenceError: Spacebars is not defined iron_layout.js:95:2

thanks!

**Comment by ianmartorell** [comment]
I'm sorry but I don't know what your problem might be. What packages are you using? I would try creating a new meteor app and testing if you have another package that's causing a conflict.
