### ISSUE TITLE
Don't declare dependency on twbs:bootstrap

### ISSUE THREAD

**Issue by jay-depot** [ianmartorell/meteor-accounts-ui-bootstrap-3#152]
After running a meteor update, I noticed that my project suddenly has twbs:bootstrap added to it. I've traced it down to two packages declaring a hard dependency on twbs:bootstrap. One of them was this one.

We use nemo64:bootstrap because it is very easy to customize, and adding twbs:bootstrap conflicts with it and causes our stylesheets to break.

Please don't declare a hard dependency on a specific bootstrap package.

**Comment by ianmartorell** [comment]
This package has a weak dependency on both twbs:bootstrap and nemo64:bootstrap, you can check the [package.js](../blob/master/package.js).

**Comment by jay-depot** [comment]
Interesting, Thanks.

So it should be the other of the two packages that caused the issue.

**Comment by jay-depot** [comment]
Yep, it was the other package, and it looks like they fixed it.

https://github.com/meteor-factory/meteor-admin-lte/issues/5
