### ISSUE TITLE
Not recognizing twbs:bootstrap?

### ISSUE THREAD

**Issue by Ntangen** [ianmartorell/meteor-accounts-ui-bootstrap-3#155]
I've used this package before successfully. Yet for some reason, when I installed it today, I get this console error message, and the accounts dropdown doesn't work:
> You have to add a Bootstrap package, i.e. meteor add twbs:bootstrap.

Thing is, I definitely have `twbs:bootstrap` already installed. Verified with `meteor list`. Is there some reason why this package wouldn't be recognizing twbs:bootstrap?

**Comment by ianmartorell** [comment]
Weird, does it happen on a barebones app? I'm not sure if a conflicting package could cause this..

**Comment by SV-Developer** [comment]
I was having this same issue. I eventually realized I had accidentally included jQuery twice (I had a minified version inside of my project). Upon deleting the extra jQuery file, the error messages disappeared! Hope that helps.

**Comment by Ntangen** [comment]
Ah ha - that was it! Thanks, @SV-Developer!
