### ISSUE TITLE
Signups forbidden when used with orion

### ISSUE THREAD

**Issue by Madsn** [ianmartorell/meteor-accounts-ui-bootstrap-3#156]
I'm unable to register new accounts through accounts-ui-bootstrap-3 after adding [orion](https://github.com/orionjs/orion) to my project.

I've tried recreating the issue in a clean project, and here is what I'm seeing:
- I have created an orion admin account (necessary in orion before regular signups are open)
- I have added `Options.set('forbidClientAccountCreation', false);` in a shared scope file
- I can signup additional users via the orion register page
- When I attempt to signup via meteor-accounts-ui-bootstrap-3 I get a "Signups forbidden" message

I know this seems very orion specific, and it might be an issue with orion or simply some incompatibility between this package and orion, but I'm hoping you might have an idea of what the issue is. Let me know if I should try creating an issue in the orion repo instead.

**Comment by ianmartorell** [comment]
I don't know what it could be, but it sounds like `Accounts.config({ forbidClientAccountCreation: true})` is being called somewhere. I don't know how Orion works so I can't tell, but maybe that option that you set didn't work properly or load early enough. I have no idea.

If you're getting the signup fields in the UI but an error message in the console, that means `Accounts.config` was only called on the server. Or maybe it was called with `forbidClientAccountCreation: false` on both and then with `forbidClientAccountCreation: true` on the client only. Hope that helps.

**Comment by Madsn** [comment]
Thank you very much for taking a look @ianmartorell, and for the fast reply. I'm not getting any errors in the console, so I don't think it's because the setting is true on the client only.

As you can see, I've created an issue in the orion repo. Hopefully they will have some idea what's going on.

**Comment by ianmartorell** [comment]
Feel free to reopen this issue if it's related to this package
