### ISSUE TITLE
passwordsSignupFields Error

### ISSUE THREAD

**Issue by pdcolvin** [ianmartorell/meteor-accounts-ui-bootstrap-3#160]
Error: Accounts.ui.config: Invalid key: passwordsSignupFields
http://localhost:3000/packages/ian_accounts-ui-bootstrap-3.js?63cca241cdb22eb485c0d8d0a06083779854adf3
Line 74

Implemented accounts-ui-bootstrap-3 following along with the "Discover Meteor" book.

**Comment by ianmartorell** [comment]
It's passwordSignupFields not passwordsSignupFields
