### ISSUE TITLE
(STDERR) ReferenceError: accountsUIBootstrap3 is not defined

### ISSUE THREAD

**Issue by tajayebi** [ianmartorell/meteor-accounts-ui-bootstrap-3#161]
After following the instructions and adding the necessary packages . I tried to add the following language support on the server side : 

accountsUIBootstrap3.map('fa', {
    _resetPasswordDialog: {
      title: 'تنظیم مجدد پاسورد',
      cancel: 'لغو',
      submit: 'ذخیره'
    },
    _enrollAccountDialog: {
      title: 'رمز عبور را وارد کنید',
      cancel: 'بستن',
      submit: 'ذخیره رمز ورود'
    }
   
});

On the server side console I am getting this error message : (STDERR) ReferenceError: accountsUIBootstrap3 is not defined

Packages I have installed are as following 

accounts-password            1.1.1  Password support for accounts
alanning:roles               1.2.13  Role-based authorization
anti:i18n                    0.4.3  Internalization: simplest package
aslagle:reactive-table       0.8.11* A reactive table designed for Meteor
email                        1.0.6  Send email messages
facts                        1.0.4  Publish internal app statistics
ian:accounts-ui-bootstrap-3  1.2.77* Bootstrap-styled accounts-ui with multi-language support.
iron:router                  1.0.9  Routing specifically designed for Meteor
meteor-platform              1.2.2  Include a standard set of Meteor packages in your app
meteorhacks:kadira           2.23.1  Performance Monitoring for Meteor
mizzao:bootstrap-3           3.3.1_1  HTML, CSS, and JS framework for developing responsive, mobile first...
mizzao:timesync              0.3.3  NTP-style time synchronization between server and client
msavin:jetsetter             1.0.20  Visual Get/Set Tool for Sessions
msavin:mongol                1.1.5  The insanely handy development package for Meteor.
reactive-var                 1.0.5  Reactive variable
showdown                     1.0.4  Moved to the 'markdown' package
tap:i18n                     1.5.1  A comprehensive internationalization solution for Meteor
tap:i18n-db                  0.4.0  Internationalization for Meteor Collections
tap:i18n-ui                  0.7.0  User interface for the tap-i18n package
twbs:bootstrap               3.3.5  The most popular front-end framework for developing responsive, mobil...
yuukan:streamy               1.2.1  Simple interface to use the underlying sockjs in a meteor application

**Comment by ianmartorell** [comment]
accountsUIBootstrap3 is only defined on the client
