### ISSUE TITLE
Need stylus update to package.js for Meteor 1.2

### ISSUE THREAD

**Issue by sferoze** [ianmartorell/meteor-accounts-ui-bootstrap-3#166]
```
Constraints on package "stylus":
* stylus@=2.511.0_1 <- top level
* stylus@1.0.0 <- ian:accounts-ui-bootstrap-3 1.2.59
```

Please update this package to use latest version of stylus so I can update to Meteor 1.2. THanks!

**Comment by ianmartorell** [comment]
It seems you're using an outdated version of the package. The dependency for Stylus is fixed on 1.2.80 #154
