### ISSUE TITLE
Suggested method for using with React?

### ISSUE THREAD

**Issue by sys13** [ianmartorell/meteor-accounts-ui-bootstrap-3#167]
I'm trying to use this with react. However, my parent node is a div, so it becomes ul > div(my component container) > li > a, which messes up the css. 

React doesn't have a way of replacing an element, so I can't use an li component container and then replace it.

I tried delving into bootstrap and replacing a bunch of li > a with div > li > a but didn't have luck. I've also tried doing ul > li > a > div (container) > li > a but the widget becomes unusable.

Any suggestions would be welcome. Thanks.

**Comment by sys13** [comment]
I gave up and started using Material-UI which has native react components. Using vanilla bootstrap with react was not a good idea.

**Comment by jacobdr** [comment]
I have been having good luck so far with [React-Bootstrap](https://react-bootstrap.github.io/) and Meteor
