### ISSUE TITLE
Autofocus the first input on opening the drop down

### ISSUE THREAD

**Issue by jms301** [ianmartorell/meteor-accounts-ui-bootstrap-3#18]
Hi there, very useful package! 

It would be nice if clicking open the drop down would auto focus the first login input. Saving on mouse clicks and all that.

**Comment by sylido** [comment]
This doesn't seem to be working anymore - 1.2.77.
The problem becomes extra crappy because the template events are stopping propagation of events on the links so you can't even do it manually yourself.

**Comment by ianmartorell** [comment]
Yeah.. I need to rewrite all that to address multiple issues, and stop stopping propagation
