### ISSUE TITLE
align = "right" and align = "left" does not work

### ISSUE THREAD

**Issue by justintime4tea** [ianmartorell/meteor-accounts-ui-bootstrap-3#181]
When using the Meteor package "accounts-ui" you can use {{> loginButtons align="right"}} within your template and the drop-down menu will be positioned so as not to run off the screen (because it's to the far right).

When I remove the Meteor package "accounts-ui" and add the packages "twbs:bootstrap" and "ian:accounts-ui-boottrap-3" this functionality is lost. align="right" and align="left" appear to do nothing.

Perhaps I'm missing something but I was under the impression this was a "drop-in" replacement for accounts-ui and the "ian:accounts-ui-bootstrap-3" documentation does mention the use of these configurations.

I am able to apply a negative margin-left to the CSS of the element using "#login-dropdown-list .dropdown-menu" as the selector but it does not keep the dropdown in the same location when a user is signed in as opposed to not signed in. When the Login dropdown text changes to username (when logged in) the dropdown is pushed further to the left leaving a non-uniform distance; kind of a "hacky" work-a-round but will suffice until fixed.

Apologies if I have missed some documentation or if this issue has already been submitted. When time provides I will try to take a look at the differences between "accounts-ui" and "ian:accounts-ui-bootstrap-3" and if I can fix it I will submit a pull-request.

**Comment by ianmartorell** [comment]
This package is sort of a drop-in replacement for `accounts-ui`. However, you need to handle the layout of your page using bootstrap. The example in the readme shows how to place the loginButtons right-aligned, but you could left align them just as easily:

```html
<div class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
        <a class="navbar-brand" href="#">Project name</a>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
             {{> loginButtons}} <!-- left aligned -->
            <li class="active"><a href="#">Link</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {{> loginButtons}} <!-- right-ailgned -->
        </ul>
    </div>
</div>
```
Bottom line, use `navbar-right` for right alignment on the parent `ul` selector.
