### ISSUE TITLE
Login seems tied to browser

### ISSUE THREAD

**Issue by tiredoftry** [ianmartorell/meteor-accounts-ui-bootstrap-3#188]
If I open two windows of the same brower (two Chrome windows or two FireFox windows) the user is logged in on both.  Logging out of one logs out of both.

If I open a Chrome window and a FireFox window, I can have different users logged in at the same time without any issue.

**Comment by tiredoftry** [comment]
This is the default of the Meteor accounts package.

**Comment by ianmartorell** [comment]
Yep, this is the expected behaviour not only in Meteor but also in almost every other website out there :P
