### ISSUE TITLE
Use 'uk' for ukrainian language, not 'ua'

### ISSUE THREAD

**Issue by epaminond** [ianmartorell/meteor-accounts-ui-bootstrap-3#190]
[ISO 639-1 for Ukrainian language](https://en.wikipedia.org/wiki/Ukrainian_language) is `uk`, not `ua` which causes issues when trying same language code to localize say `momentjs` and `accountsUIBootstrap3`.

**Comment by ianmartorell** [comment]
Fixed in 485663c82d6bde7778e98c7b8afb0a1053052b47
