### ISSUE TITLE
No login services configured

### ISSUE THREAD

**Issue by javidrashid** [ianmartorell/meteor-accounts-ui-bootstrap-3#191]
I removed the accounts-ui package, have bootstrap package already and then I did:

meteor add ian:accounts-ui-bootstrap-3

and have added the following html in my navbar template:

 <ul class="nav navbar-nav navbar-right">
            {{> loginButtons}} 
        </ul>

After rebooting meteor, I see "No login services configured" messages instead of Login/Signup dropdown. Am I supposed to do anything else to configure this thing to get it working.

FYI, my meteor version is 1.2.1

**Comment by ianmartorell** [comment]
Did you add the `accounts-password` package? You'll need at least one accounts plugin like that one or  `accounts-google`, `accounts-facebook`, `accounts-github`, etc.

**Comment by javidrashid** [comment]
I am not using any third party service providers like facebook, google et-al. I hadn't done meteor add accounts-password thats why the problem. Thanks for the pointer though.
