### ISSUE TITLE
Meteor Accounts.ui.config not working with Google

### ISSUE THREAD

**Issue by artitw** [ianmartorell/meteor-accounts-ui-bootstrap-3#23]
I am simply trying to log in with Google and get the permissions for Calendar, etc. However, my code in the client only prompts user signing in for offline access. Why is it not asking for the calendars, etc.? Also, it is not forcing the approval prompt. I'm using ian:accounts-ui-bootstrap-3

    Accounts.ui.config({
     	requestPermissions: {
    		google: 
    		['https://www.googleapis.com/auth/calendar',
    		'https://www.googleapis.com/auth/calendar.readonly',
    		'https://www.googleapis.com/auth/userinfo.profile',
    		'https://www.googleapis.com/auth/userinfo.email',
    		'https://www.googleapis.com/auth/tasks'], 
    		forceApprovalPrompt: true
     	}, 
     	forceApprovalPrompt: {google: true},
      	requestOfflineToken: {google: true},
      	passwordSignupFields: 'EMAIL_ONLY',
      	extraSignupFields: []
    });

http://stackoverflow.com/questions/27468270/meteor-accounts-ui-config-not-working-with-google

**Comment by ianmartorell** [comment]
I would like to get this fixed, and I'm trying to login with the official `accounts-ui` package and the config you described in your first post. I'm getting the exact behaviour than with this package, the user is automatically logged in with no prompts. Did you get this working with the official or any other accounts package?

**Comment by artitw** [comment]
Hey, yes it works with the official `accounts-ui`. That's what I'm using now, but I'd much prefer to use this package if it gets fixed. Thanks!

**Comment by ianmartorell** [comment]
I've tested this with the latest version 1.2.21 and it works, can you confirm it?

**Comment by artitw** [comment]
Hi Ian, 

It now prompts for offline access; however, it does not pass the refreshToken for me to use. Do you know why that might be? Thanks!

Art
