### ISSUE TITLE
Common server Accounts error messages are not translated (e.g. "User not found")

### ISSUE THREAD

**Issue by obiwarn** [ianmartorell/meteor-accounts-ui-bootstrap-3#28]
How to integrate t9n pcks like mrt:accounts-t9n ?

https://atmospherejs.com/softwarerero/accounts-t9n

**Comment by ianmartorell** [comment]
I added translations to the error messages within this package, what language were you looking for?

We could also look into integrating with accounts-t9n in the future

**Comment by obiwarn** [comment]
I use the German transltion which works great. Only the userNotFound Message is not translated.

**Comment by ianmartorell** [comment]
works now!
