### ISSUE TITLE
Blank Meteor Response After Install

### ISSUE THREAD

**Issue by reustle** [ianmartorell/meteor-accounts-ui-bootstrap-3#35]
As soon as I meteor add ian/accounts-ui-bootstrap-3, assuming that is this project, meteor will only show me a blank page and these errors. Is this due to an error on my part? I have essentially a bare-bones fresh meteor project with no code changes.

```
Uncaught Error: There are multiple templates named '_loginButtonsLoggedIn'. Each template needs a unique name.
Uncaught TypeError: Cannot read property 'accountsUIBootstrap3' of undefined
```

Output of install
```
srair:humans reustle$ meteor add ian:accounts-ui-bootstrap-3

Changes to your project's package version selections:

anti:i18n                    added, version 0.4.3
handlebars                   added, version 1.0.2
ian:accounts-ui-bootstrap-3  added, version 1.2.8
stylus                       added, version 1.0.6
twbs:bootstrap               added, version 3.3.1


ian:accounts-ui-bootstrap-3: Bootstrap-styled accounts-ui with multi-language support.
```

I am doing this on a boilerplate demo app (no JS modifications yet, and html page is hello world). Here are my installed packages and versions

```
accounts-password   1.0.5  Password support for accounts
accounts-ui         1.1.4  Simple templates to add login widgets to an app
autopublish         1.0.2  Publish the entire database to all clients
insecure            1.0.2  Allow all database writes by default
meteor-platform     1.2.1  Include a standard set of Meteor packages in your app
mizzao:bootstrap-3  3.3.1_1  HTML, CSS, and JS framework for developing responsive, mobile first projects on the web.
```

Any insight is appreciated!

**Comment by ianmartorell** [comment]
Multiple Bootstrap packages were also causing problems, so `twbs:bootstrap` is no longer a hard dependency, as per #34 . So what I said about "you can safely remove mizzao:bootstrap-3, as this package will already add twbs:bootstrap as a dependency" is no longer true. You can keep using `mizzao:bootstrap-3`, but we recommend you switch to `twbs:bootstrap`.

**Comment by reustle** [comment]
Thanks Ian!
