### ISSUE TITLE
Problem logging in with Facebook

### ISSUE THREAD

**Issue by Wolsten** [ianmartorell/meteor-accounts-ui-bootstrap-3#45]
Hi Ian,

Apologies for troubling you again. I have tried to follow your advice here with the following steps:

1. meteor add accounts-facebook
2. Set up app in Facebook
3. Selected Sign in/up
4. Selected Configure Facebook, entered details (App ID and App Secret) in the popup window and then clicked Save Configuration
5. Selected Sign in/up
6. Selected Sign in with Facebook

The end point of this is a blank popup window with the following url:

	http://localhost:3000/_oauth/facebook?close&code=AQBQvYgn...very long code

I also set my config as follows:

```javascript
Accounts.ui.config({
  requestPermissions: {
    facebook: ['email', 'public_profile', 'user_friends']
  },
  passwordSignupFields: 'USERNAME_AND_OPTIONAL_EMAIL'
});
```

I have tried this on three browsers (Chrome, Safari and IE) with the same result.

Best wishes

Steve

**Comment by ianmartorell** [comment]
I really don't see what you're doing wrong. I've created a meteor project from scratch and done just the bare minimum to get Facebook auth working and it is working. Please check [this](https://github.com/ianmartorell/facebook-test) out and see what's different from what you're doing.

**Comment by Wolsten** [comment]
Hi Ian, thanks for the feedback. I downloaded your example and tried running it with the same results:

![login](https://cloud.githubusercontent.com/assets/9863374/5797487/b0d5bad6-9fb2-11e4-825f-45dd08c84ea9.jpg)

FYI I am running this on my MacBook behind my home firewall. 

BTW - I notice you installed twbs-package which I hadn't previously, though I have the bootstrap functionality working fine in my app.

**Comment by Wolsten** [comment]
Hi Ian,

Just to let you know that I managed to login using my Facebook account just now using your skeleton app. I have not made any changes so I am mystified as to why this is working now. I'll re-try my own app and see if that is working also. Clearly though it isn't your code causing the problem (but you knew that!).  I will let you know if I find out what caused the problem as it may be of interest to you.

Best wishes

Steve

**Comment by Wolsten** [comment]
Ian,

I sussed it. It was because the address in my browser had been replaced with my local ip address rather than local host and the redirect was rejected because of the different frame origins.

Sorry to have troubled you with this but may be worth highlighting to other that might make the same mistake as myself.

Best wishes

Steve

**Comment by ianmartorell** [comment]
I see! I should have noticed before, I was clueless as to what it could be. Thanks for sharing though, it's an easy mistake to make.
