### ISSUE TITLE
How does the server know which language is selected on account creation?

### ISSUE THREAD

**Issue by obiwarn** [ianmartorell/meteor-accounts-ui-bootstrap-3#46]
So it can translate the verificationEmails

**Comment by ianmartorell** [comment]
Wow, I let some time go on this one. Hope you figured it out yourself, but if you look in [i18n.js](https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3/blob/master/i18n.js) the package exposes a `accountsUIBootstrap3.getLanguage()` function.
