### ISSUE TITLE
Is there a notification on account creation?

### ISSUE THREAD

**Issue by obiwarn** [ianmartorell/meteor-accounts-ui-bootstrap-3#47]
So I can show an alert or sth. to the user that he/she needs to verify the email address.

**Comment by newswim** [comment]
:+1:

**Comment by reustle** [comment]
While I don't have the answer for you, this (server side) method might be helpful

http://docs.meteor.com/#/full/accounts_oncreateuser

**Comment by ianmartorell** [comment]
You could do something like this:

```javascript
Meteor.autorun(function(){
  var user = Meteor.user();
  if (!user || !user.profile) return;

  if (!user.emails[0].verified) {
    // Show an alert or something
  }
});
```

This would prompt the user to verify the email address on every login, or you could modify it so it instead checks for a different flag and sets it to true the first time it runs.

**Comment by dandv** [comment]
This seems out of scope for this package?

**Comment by ianmartorell** [comment]
Yeah
