### ISSUE TITLE
Provide additional options for Accounts.onCreateUser

### ISSUE THREAD

**Issue by dropfen** [ianmartorell/meteor-accounts-ui-bootstrap-3#52]
Hi, I guess the title is self explained. So how can I pass some additional options values, which I then can validate on the server side. In my case, I need a affiliate userId which "gave" the link to this new user, so I can provide some points for the affiliate, or so. It would be cool to have some Hooks on the client side as well.

Thank you

**Comment by ianmartorell** [comment]
What about adding the referrer's id as a field in the newly created user so you can check it in `onCreateUser`?

**Comment by dropfen** [comment]
hi ian, yes you are right, i could do it with a field, but the fields values are going to user.profile.. It's possible to solve, I know. However, just thought it would be cool to have some kind of Hook or Optional method, implemented by the user..

on lIne 477 instead of options = {};

var options = (typeof getCustomSignupOptions === 'function') getCustomSignupOptions() : {};
if (!(options instanceof Object)) options = {}

So then it's much simplier to pass some custom options values, just by creating these function on the client side..

getCustomSignupOptions = function() {
  return {
    refId: Session.get('refId') // Or whatever else..
  }
}

What do you think?

**Comment by ianmartorell** [comment]
I think it's a good idea! Sorry it took so long.

**Comment by dropfen** [comment]
Thank you for implementing, I just updated the readme.
https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3/pull/66

**Comment by ianmartorell** [comment]
Hey, I changed `setCustomSignupOptions` to `accountsUIBootstrap3.setCustomSignupOptions` for consistency.

**Comment by dropfen** [comment]
Sure, it makes sense.
