### ISSUE TITLE
Exception from Tracker afterFlush function: undefined is not a function

### ISSUE THREAD

**Issue by rdewolff** [ianmartorell/meteor-accounts-ui-bootstrap-3#58]
I have the same issue as already opened/closed (cf. https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3/issues/15) but am not using any jquery external lib.

The packages am using are the following :
```
meteor-platform
insecure
iron:router
less
nemo64:bootstrap
houston:admin
matteodem:easy-search
rdewolff:temple-admintool
ian:accounts-ui-bootstrap-3
dburles:mongo-collection-instances
```

Any idea? Need more info?

**Comment by rdewolff** [comment]
Seems to be a bootstrap problem. If I add the package you mention in the readme (twbs:bootstrap), the error goes away, but my bootstrap menu (nav-bar dropdown specifically) doesn't work anymore. 

Any idea how to fix that properly?

**Comment by ianmartorell** [comment]
It might be because your bootstrap package isn't loading before this one. I've just added it as a weak dependency, tell me if that fixes it!

**Comment by lpatmo** [comment]
For what it's worth, I saw the same error as the OP... meteor-account-ui-bootstrap-3 only worked after I installed twbs:bootstrap.

**Comment by ianmartorell** [comment]
What bootstrap package were you using before?

**Comment by Sinetheta** [comment]
Can confirm that I also get this error when using `nemo64:bootstrap` but it goes away if I swap out for twbs:bootstrap. Which is unfortunate because I'd like to be using Bootstrap from source instead of a compiled version.

**Comment by ianmartorell** [comment]
I see.. I don't have much time too look into it right now, but I will try to get it resolve as soon as possible.

**Comment by ianmartorell** [comment]
I don't have any issues with `nemo64:bootstrap` so I'm closing this for now. Feel free to re-open.
