### ISSUE TITLE
cannot include package locally

### ISSUE THREAD

**Issue by kahon** [ianmartorell/meteor-accounts-ui-bootstrap-3#60]
I try to include package locally cloning repository on METEOR_APP_HOME/packages/accounts-ui-b . Then I type on METEOR_APP_HOME "meteor add accounts-ui-b" but return:

 => Errors while parsing arguments:           
                                              
While adding package accounts-ui-b:
error: no such package

If I do the same with this package it is working: 
https://github.com/mangasocial/meteor-accounts-ui-bootstrap-3/

**Comment by ianmartorell** [comment]
Well, you typed `accounts-ui-b`, the full name of the package is `ian:accounts-ui-bootstrap-3`, you need to use the full name to add it.

**Comment by kahon** [comment]
I does not mean that

**Comment by ianmartorell** [comment]
Si lo prefieres puedes escribir en castellano xD

**Comment by kahon** [comment]
Quiero añadir el paquete de forma local. Entonces descargo el código fuente en `METEOR_APP_HOME/packages/accounts-ui-b` . Entonces en la consola escribo (en el directorio METEOR_APP_HOME) "meteor add accounts-ui-b" pero me da error:

``` 
=> Errors while parsing arguments:

While adding package accounts-ui-b:
error: no such package
```
Si hago lo mismo con el paquete de mangasocial no me da ese error:
https://github.com/mangasocial/meteor-accounts-ui-bootstrap-3/

**Comment by ianmartorell** [comment]
Ya, eso ya lo había entendido, pero es que el paquete no se llama `accounts-ui-b`, por eso no te deja añadirlo. Independientemente del nombre de la carpeta en el que clones el repo, el nombre del paquete viene dado por lo que hay en [package.js](https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3/blob/master/package.js), así que tendrás que añadirlo usando `ian:accounts-ui-bootstrap-3`.

**Comment by kahon** [comment]
No es así, porque si lo hago con el paquete de mangasocial tal cual igual que con este paquete si me funciona. Cuando haces el `meteor add` de forma local el nombre del paquete es el nombre del directorio que está dentro de "packages".

**Comment by kahon** [comment]
Como ejemplo te digo lo que estoy haciendo: 
He puesto dentro de packages tu código y el de mangasocial en dos carpetas distintas. Una se llama manga y la otra se llama ian. Así que hago `meteor add manga` y funciona, si hago `meteor add ian` me da error.

**Comment by ianmartorell** [comment]
Con el paquete de mangasocial te funciona porque en su `package.js` no se especifica el nombre del paquete. Como desde Meteor 0.9 los nombres de los paquetes tienen que seguir la convención `propietario:paquete` y para no tener problemas con `:` en nombres de carpetas cuando testeamos de forma local, se especifica el nombre en package.js y así el de la carpeta es irrelevante. Por eso para añadir este, tendrás que usar `ian:accounts-ui-bootstrap-3`, o si quieres usar el de la carpeta borra esa línea de `package.js`.

**Comment by kahon** [comment]
Si elimino el nombre del paquete si me lo hace de forma local. Si pongo ian:accounts-ui-boostrap-3 se lo descarga del servidor. Quizás haya alguna manera de que lo pille localmente y con su nombre. Gracias por la aclaración.

**Comment by ianmartorell** [comment]
¿Cómo sabes que se lo descarga del servidor? Yo hago esto para probar nuevas versiones antes de publicarlas en Atmosphere y funciona a la perfección. Si quieres estar seguro, puedes añadir el paquete con  ian:accounts-ui-bootstrap-3` y entonces subir el número de la versión en package.js. Si al hacer `meteor update` se actualiza a la versión "nueva" sin publicar, es que estás trabajando localmente.

**Comment by kahon** [comment]
Lo probé haciendo cambios locales y no viéndose reflejados en la aplicación. He probado a poner el nombre del directorio `ian:accounts-ui-bootstrap-3` (completo) dentro packages y si lo coge de forma local. Esa era la clave.
