### ISSUE TITLE
Cannot see all labels in mobile webpage looking

### ISSUE THREAD

**Issue by kahon** [ianmartorell/meteor-accounts-ui-bootstrap-3#61]
![screenshot_2015-02-02_1248](https://cloud.githubusercontent.com/assets/615981/6000131/695cb924-aada-11e4-905b-80a38078001d.png). 
I have test in two mobiles.
Windows Phone 8.1 Allows to pinch and slide to see all labels.
Android (Unknown version) does not allow to pinch and slide. It is not possible to access to all labels. Screenshot one is in Android system.

**Comment by ianmartorell** [comment]
I don't really know what the problem is as I can't replicate it. I don't have a Windows Phone but on my Nexus 5 it works great, you can slide to see the rest of the form. It also doesn't get "cut" like in your screenshot. Have you tried on Chrome for Android?

**Comment by kahon** [comment]
It is native browser. I think it is 2.3.4 Android version. I think Android 4+ is working well.

**Comment by ianmartorell** [comment]
Well, that must be it then. It's a pretty old Android version and I don't know what the error might be, so I can't support it.
