### ISSUE TITLE
Error: There are multiple templates named '_loginButtonsLoggedIn'

### ISSUE THREAD

**Issue by leonsp** [ianmartorell/meteor-accounts-ui-bootstrap-3#64]
Whenever I add ian:accounts-ui-bootstrap-3 to my Meteor project, the app goes blank and the web console has the following errors:

The connection to ws://localhost:3000/sockjs/920/ug0fo9gw/websocket was interrupted while the page was loading. ddp.js:1344
Error: There are multiple templates named '_loginButtonsLoggedIn'. Each template needs a unique name. templating.js:59
TypeError: Package['ian:accounts-ui-bootstrap-3'] is undefined global-imports.js:7
ReferenceError: Template is not defined template.layout.js:2
ReferenceError: Template is not defined template.nav.js:2
ReferenceError: Template is not defined template.job_index.js:2
ReferenceError: Template is not defined template.hello.js:2
ReferenceError: Accounts is not defined account.js:1
ReferenceError: Session is not defined client.js:2
ReferenceError: Spacebars is not defined accounts-ui-unstyled.js:634
ReferenceError: Template is not defined twbs_bootstrap.js:2358
ReferenceError: Spacebars is not defined iron_layout.js:95
"Exception in defer callback: DynamicTemplate.prototype._attachEvents@http://localhost:3000/packages/iron_dynamic-template.js?d425554c9847e4a80567f8ca55719cd6ae3f2722:430:1
DynamicTemplate.prototype.events@http://localhost:3000/packages/iron_dynamic-template.js?d425554c9847e4a80567f8ca55719cd6ae3f2722:414:3
Controller@http://localhost:3000/packages/iron_controller.js?b02790701804563eafedb2e68c602154983ade06:243:3
RouteController<.constructor@http://localhost:3000/packages/iron_router.js?a427868585af16bb88b7c9996b2449aebb8dbf51:104:5
Iron.utils.extend/ctor@http://localhost:3000/packages/iron_core.js?d966a1f70c94792fd94c8a155bdbef9bec5e0047:159:5
Route.prototype.createController@http://localhost:3000/packages/iron_router.js?a427868585af16bb88b7c9996b2449aebb8dbf51:830:18
Router.prototype.createController@http://localhost:3000/packages/iron_router.js?a427868585af16bb88b7c9996b2449aebb8dbf51:1120:18
Router.prototype.dispatch@http://localhost:3000/packages/iron_router.js?a427868585af16bb88b7c9996b2449aebb8dbf51:1683:18
onLocationChange@http://localhost:3000/packages/iron_router.js?a427868585af16bb88b7c9996b2449aebb8dbf51:1772:20
Tracker.Computation.prototype._compute@http://localhost:3000/packages/tracker.js?517c8fe8ed6408951a30941e64a5383a7174bcfa:296:5
Tracker.Computation@http://localhost:3000/packages/tracker.js?517c8fe8ed6408951a30941e64a5383a7174bcfa:214:5
Tracker.autorun@http://localhost:3000/packages/tracker.js?517c8fe8ed6408951a30941e64a5383a7174bcfa:487:11
Router.prototype.start@http://localhost:3000/packages/iron_router.js?a427868585af16bb88b7c9996b2449aebb8dbf51:1765:31
Router/</<@http://localhost:3000/packages/iron_router.js?a427868585af16bb88b7c9996b2449aebb8dbf51:968:9
.withValue@http://localhost:3000/packages/meteor.js?81e2f06cff198adaa81b3bc09fc4f3728b7370ec:949:17
withoutInvocation/<@http://localhost:3000/packages/meteor.js?81e2f06cff198adaa81b3bc09fc4f3728b7370ec:434:26
Meteor.bindEnvironment/<@http://localhost:3000/packages/meteor.js?81e2f06cff198adaa81b3bc09fc4f3728b7370ec:977:17
onGlobalMessage@http://localhost:3000/packages/meteor.js?81e2f06cff198adaa81b3bc09fc4f3728b7370ec:371:11
" meteor.js:887

These are the packages I have installed:
meteor-platform
iron:router
accounts-ui
accounts-password
email
twbs:bootstrap
ian:bootstrap-3-theme
vsivsi:job-collection

**Comment by ianmartorell** [comment]
`meteor remove accounts-ui` and it'll work

**Comment by leonsp** [comment]
Thank you, that worked!
