### ISSUE TITLE
add loggedOut template+helper

### ISSUE THREAD

**Issue by brugnara** [ianmartorell/meteor-accounts-ui-bootstrap-3#69]
I need to add a "privacy" checkbox that user must check in order to complete registration. There's a chance to achieve this with this plugin?

Many thanks.

**Comment by ianmartorell** [comment]
You can bind the privacy checkbox to a Session variable, then attach this variable to `setCustomSignupOptions` like explained in the readme and check it to confirm account creation on [Accounts.onCreateUser](http://docs.meteor.com/#/full/accounts_oncreateuser)

**Comment by brugnara** [comment]
This is ok, many thanks.
There's a chance to add some custom HTML to the accounts-ui-bs3 template? (like the checkbox it self).
I'm thinking of dinamically creating with jquery and then append it. Am I doing the right/simplest way?

To say this concisely, I'm missing the ** _loginButtonsAdditionalLoggedInDropdownActions** counterparts when loggedOut :)

Thanks again.

**Comment by ianmartorell** [comment]
You can now do what you want by adding extra signup fields as explained [in the readme](https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3#custom-signup-options)

**Comment by brugnara** [comment]
Thank you for the great job! Can I ask you when it will be available on atmosphere? There are only the 1.2.28 version. Many thank again.

**Comment by ianmartorell** [comment]
It's available now!

**Comment by brugnara** [comment]
You will hate me... I can't get this working. Now I have v1.2.30 but I can't see extra fields. I've checked the source code and the var name seems ok but nothing happens. There a `magic` place where to put this `Accounts.ui.config` call? Many thanks.

**Comment by ianmartorell** [comment]
Well... it turns out it's not your fault. I'm not sure why but if you don't set the `requestPermissions` property then the Accounts.ui.config call doesn't do anything. You can use this for now:

```javascript
Accounts.ui.config({
    requestPermissions: {
        google: []
    },
    extraSignupFields: [{
        fieldName: 'first-name',
        fieldLabel: 'First name',
        inputType: 'text',
        visible: true,
        saveToProfile: true
    }, {
        fieldName: 'last-name',
        fieldLabel: 'Last name',
        inputType: 'text',
        visible: true,
        saveToProfile: true
    }, {
        fieldName: 'terms',
        fieldLabel: 'I accept the terms and conditions',
        inputType: 'checkbox',
        visible: true,
        saveToProfile: false
    }]
});
```
I'll look into it.

**Comment by ianmartorell** [comment]
See https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3-test
