### ISSUE TITLE
Crash when password (again) field gets focus in Safari

### ISSUE THREAD

**Issue by lvergos** [ianmartorell/meteor-accounts-ui-bootstrap-3#72]
application crashes when password (again) field gets focus.
To reproduce use Safari:
- click the Sign in / up  link
- click the username field
- click the create account link
- click the password (again) field

environment: 
Safari                 7.1
meteor               1.0.3.1
accounts-password            1.0.6  Password support for accounts
autopublish                  1.0.2  Publish the entire database to all clients
ian:accounts-ui-bootstrap-3  1.2.30  Bootstrap-styled accounts-ui with multi-language support.
insecure                     1.0.2  Allow all database writes by default
meteor-platform              1.2.1  Include a standard set of Meteor packages in your app
twbs:bootstrap               3.3.2  Bootstrap (official): the most popular HTML/CSS/JS framework for r...

**Comment by ianmartorell** [comment]
It doesn't crash on me, I'm using Safari 8.0.3 on OS X 10.10.2. Can you try with [this app](https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3-test)? You might have to delete the packages folder and readd this package since I'm using it for local testing.

**Comment by lvergos** [comment]
Yes the crash still happened in that project. It seems it was an issue with the version of safari I was using, the problem went away after upgrading to safari 7.1.3

**Comment by ianmartorell** [comment]
Okay!
