### ISSUE TITLE
new Bootstrap Icons (v.3.3.2.)

### ISSUE THREAD

**Issue by daniel-sandu** [ianmartorell/meteor-accounts-ui-bootstrap-3#73]
Hy, 

First of all great job with this package! Works well. Just a question. It seems there are new icons in bootstrap as of v3.3.2. (for example: glyphicon glyphicon-apple, glyphicon glyphicon-hourglass). I tried to overwrite the fonts, but I can't make them work. Any upgrade on this matter in the near future?

**Comment by ianmartorell** [comment]
Hey, thanks! Are you saying the new icons don't work? In any case, this package doesn't provide Bootstrap itself, so it will depend on what Bootstrap package you're using. If you're using the recommended twbs:bootstrap and there's something that's not working I suggest you open an issue [here](https://github.com/MeteorPackaging/bootstrap).

**Comment by daniel-sandu** [comment]
Ah, I see. the problem was the version of bootstrap. Solved it now. Thanks for your speedy anwser. I will close the issue now. Cheers.

**Comment by ianmartorell** [comment]
Glad you solved it!
