### ISSUE TITLE
Translation problem

### ISSUE THREAD

**Issue by falcondamian** [ianmartorell/meteor-accounts-ui-bootstrap-3#75]
Hi,
I'm a Spanish developer and I'm using this fantastic package, but I found a translation that doesn't seem to be correct : 

usernameOrEmail: "Usuario o contraseña"  should be "Usuario o correo electrónico"

I've corrected it using the map function. Hope this help.

**Comment by ianmartorell** [comment]
Wow you're totally right, I'm a Spanish speaker myself but I use the package without the username feature turned on, so I didn't see it. Thanks for spotting it!
