### ISSUE TITLE
Configure Modal Isn't 100% Wide

### ISSUE THREAD

**Issue by reustle** [ianmartorell/meteor-accounts-ui-bootstrap-3#76]
The configuration modals are not displaying 100% (see screenshot 1). I was able to fix it by disabling the 2nd and 3rd styles in screenshot 2. Seeing that these styles exist in the first place, is this intentional?

![accounts-ui](https://cloud.githubusercontent.com/assets/304560/6313017/374b72ac-b9c8-11e4-8e1a-682b42bfd390.png)

![accounts-ui-styles](https://cloud.githubusercontent.com/assets/304560/6313016/332841fa-b9c8-11e4-99fc-f15de0e4ec14.png)

**Comment by ianmartorell** [comment]
I guess there is no reason, I'll remove it
