### ISSUE TITLE
don't auto closed when I click any link out of "UI"?

### ISSUE THREAD

**Issue by yuomtheara** [ianmartorell/meteor-accounts-ui-bootstrap-3#77]
The first time I click on `ui`, it show for type the user name and password,  but i don't type any thing and i move mouse pointer to click any link out of the `ui`, so `ui` should be closed auto (but don't).
It is OK (close) if I click it again.
pl help me why?

**Comment by marc-lebourdais** [comment]
fwiw I proposed a fix for this in https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3/compare/master...marc-lebourdais:patch-1

**Comment by yuomtheara** [comment]
Very thanks for your reply.
