### ISSUE TITLE
How to add custom fields in sign-in and forgot-password ?

### ISSUE THREAD

**Issue by julienrott** [ianmartorell/meteor-accounts-ui-bootstrap-3#80]
Hi,

Thanks for your package, it is awesome. Especially the extra signup fields feature.
I'd like to use it to implement 2-factor authentication with yubikey.
For this I'd need an extra field for the One Time Password in the signup, signin and forgot password templates.
I guess this is not possible for now. If I fork your project, how can I add this ?

**Comment by ianmartorell** [comment]
Hi Julien, thank you! As of now it's not implemented, but you can do it yourself. Just take a look at how the extra signup fields are implemented and try to replicate it for signin and forgot password. Look at the signup function at line 478 of `login_buttons_dropdown.js` for how the fields are parsed (line 526 exactly) and lines 81-83 and 122-134 of `login_buttons_dropdown.htlm` for how it's shown in the UI. You'll have to replicate this for the signin and forgotPassword functions. I would do like to do it myself but I don't have much free these days, so if you manage to do something others can use you are welcome to submit a pull request!
