### ISSUE TITLE
How to custom signup options with select box of gender (Male and Female)?

### ISSUE THREAD

**Issue by yuomtheara** [ianmartorell/meteor-accounts-ui-bootstrap-3#84]
How to custom signup options with select box of gender (Male and Female)?

**Comment by ianmartorell** [comment]
This package supports custom signup options, but only for text fields and checkboxes at the moment. You could fork it and modify it yourself to add the `select` functionality. Look at the file login_buttons_dropdown.html at line 125

**Comment by yuomtheara** [comment]
thanks

**Comment by greenwolfe** [comment]
@yuomtheara  I'm also looking for a select box in the input field.  If you implemented this successfully, can you post your code here?
Thanks

**Comment by ianmartorell** [comment]
There is a pull request for this #124
