### ISSUE TITLE
don't want to change user login when create new?

### ISSUE THREAD

**Issue by yuomtheara** [ianmartorell/meteor-accounts-ui-bootstrap-3#85]
I create new form to create new user by myself (When login).
But i don't want to change user login when create new (stay the old user account).

**Comment by ianmartorell** [comment]
If you don't want to log in to the new account, you should call [`Accounts.createUser`](http://docs.meteor.com/#/full/accounts_createuser) from the server. You can do this with a Meteor call.

**Comment by yuomtheara** [comment]
thanks
