### ISSUE TITLE
Reset Password does not send an email

### ISSUE THREAD

**Issue by sudhirsoneji** [ianmartorell/meteor-accounts-ui-bootstrap-3#87]
Reset password dialog displays a  message that email was sent but no email was received.

**Comment by curioussavage** [comment]
Maybe it would be helpful to explain what you did to set up email on your app. If you have not done that yet then that is the problem.

**Comment by sudhirsoneji** [comment]
You are correct. I need to check that first.

I am a little rusty and getting my hands on programming after 15 long years. Lot of things have changed and evolved from my VB/ASP/JScript days and am learning new things.

Appreciate your prompt response.
