### ISSUE TITLE
Disable Signup

### ISSUE THREAD

**Issue by jesseflorig** [ianmartorell/meteor-accounts-ui-bootstrap-3#88]
Is it possible to disable signup via override?

**Comment by ianmartorell** [comment]
Yes, use [Accounts.config](http://docs.meteor.com/#/full/accounts_config) just like with the official Accounts.ui package

**Comment by jesseflorig** [comment]
Ah, of course. Thank you.

**Comment by JackyXiong** [comment]
Why I use `Accounts,config({forbidClientAccountCreation: true})` in server, the button of 'Join' is still appear.
it's not work. Is this a bug?
