### ISSUE TITLE
Override login buttons text

### ISSUE THREAD

**Issue by jesseflorig** [ianmartorell/meteor-accounts-ui-bootstrap-3#89]
Is it possible to override login dropdown/button text?

**Comment by ianmartorell** [comment]
You could override the language you're using as explained in the Readme. I haven't tested this though.

```javascript
accountsUIBootstrap3.map('es', {
    _resetPasswordDialog: {
      title: 'Restablece tu contraseña',
      cancel: 'Cancelar',
      submit: 'Guardar'
    },
    _enrollAccountDialog: {
      title: 'Escribe una contraseña',
      cancel: 'Cerrar',
      submit: 'Guardar contraseña'
    },
    // ...
})

**Comment by jesseflorig** [comment]
This makes sense. I guess the only problem with this specific to my issue is that I'd like to remove the "/ Join" from the login button.

As far as I can tell the "Sign In", "/", and "Join" values are all separated with no way to override the "/".

**Comment by jesseflorig** [comment]
Ok, so using the correct Accounts config takes care of this:

`
Accounts.config({
	forbidClientAccountCreation: true
});
`

Sorry for the non-issue!

**Comment by ianmartorell** [comment]
Yes, that's right! It already checks if signup is enabled and hides what doesn't apply.
