### ISSUE TITLE
App no longer works after install

### ISSUE THREAD

**Issue by BrooklynC** [ianmartorell/meteor-accounts-ui-bootstrap-3#90]
Installing this package seems to prevent my app from working (all content disappears from browser).  I added accounts-password, accounts-ui and this package and checked after each install.  If I remove this package, the app works fine again.

**Comment by ianmartorell** [comment]
You need to remove `accounts-ui` for this package to work.

**Comment by awhitford** [comment]
I suggest that this little note be added to this README found here:  https://atmospherejs.com/ian/accounts-ui-bootstrap-3

**Comment by ianmartorell** [comment]
How about now :)

**Comment by BrooklynC** [comment]
Thanks Ian, I had misread the Readme before my original post.
