### ISSUE TITLE
problem with "sing in / sing up" label when add "ostrio:i18n"?

### ISSUE THREAD

**Issue by yuomtheara** [ianmartorell/meteor-accounts-ui-bootstrap-3#97]
problem with "sing in / sing up" label when add "ostrio:i18n"?

**Comment by ianmartorell** [comment]
It looks like ostrio:i18n is using the same `{{i18n ...}}` Spacebars tags as `anti:i18n`, so they're not compatible. That's the one I use for this package so I suggest you switch over if possible.
