### ISSUE TITLE
how to integrate with "softwarerero:accounts-t9n"?

### ISSUE THREAD

**Issue by yuomtheara** [ianmartorell/meteor-accounts-ui-bootstrap-3#98]
how to integrate with "softwarerero:accounts-t9n"?

**Comment by ianmartorell** [comment]
I see that package translates error messages for the meteor accounts packages, but this one has built in translations, so I don't see why you'd want to integrate them?

**Comment by yuomtheara** [comment]
Now i use build in translates on this package, it work fine.
